### ISSUE TITLE
ReferenceError: Map is not defined

### ISSUE THREAD

**Issue by FigBug** [LinusU/node-appdmg#115]
I'm on OSX 10.11.5 and I get the following error:

ReferenceError: Map is not defined
    at Object.<anonymous> (/usr/local/lib/node_modules/appdmg/node_modules/ds-store/node_modules/tn1150/index.js:19:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/appdmg/node_modules/ds-store/lib/entry.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by FigBug** [comment]
Maybe not a appdmg error after all, my version of node too old? But now I get:

module.js:568
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:568:18)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/appdmg/node_modules/ds-store/node_modules/macos-alias/lib/create.js:7:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)

**Comment by FigBug** [comment]
That was it

**Comment by LinusU** [comment]
Yeah, it seems like `Map` is only available in 0.12 and newer. For anyone else getting "Error: Module did not self-register.", it's usually when you upgrade your Node.js version but have older compiled versions of modules. Running `npm rebuild` should fix it...
