### ISSUE TITLE
breaks on node 7.6

### ISSUE THREAD

**Issue by chino23** [LinusU/node-appdmg#131]
I've upgraded from node 6 to 7.x and now can't use it anymore:

````
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/usr/local/lib/node_modules/appdmg/node_modules/macos-alias/build/Release/volume.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/appdmg/node_modules/macos-alias/lib/create.js:7:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
````

**Comment by cstruct** [comment]
You have to [rebuild](https://docs.npmjs.com/cli/rebuild) native dependencies.

**Comment by LinusU** [comment]
As said in the error message as well :)

> was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).

**Comment by chino23** [comment]
yeah sorry, i was a bit fast on that. got it working :)
