### ISSUE TITLE
Bless - ERROR: Illegal option --folder

### ISSUE THREAD

**Issue by artemgurzhii** [LinusU/node-appdmg#140]
This package is being used by [ember-electron](https://github.com/felixrieseberg/ember-electron/issues/240) which I use. And I'm having the following problem.

```bash
Command failed: bless --folder /Volumes/AppName --openfolder /Volumes/AppName

ERROR: Illegal option --folder

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 413.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------

Error: Command failed: bless --folder /Volumes/AppName --openfolder /Volumes/AppName

ERROR: Illegal option --folder

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 413.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:189:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```
As I'm seeing in [#14](https://github.com/LinusU/node-appdmg/issues/14) you are about to make it fully cross-platform but is there any temporary fix or any other way to avoid this?

**Comment by LinusU** [comment]
Unfortunately, there is no current workaround. At the moment macOS is required.
