### ISSUE TITLE
appdmg broken in Travis since new update to 0.6.0

### ISSUE THREAD

**Issue by vadi2** [LinusU/node-appdmg#180]
We use node 12.3.1 in our Travis instance (build log: https://travis-ci.org/Mudlet/Mudlet/jobs/538552277) and the new update has broken appdmg:

```
/Users/travis/.npm-global/bin/appdmg -> /Users/travis/.npm-global/lib/node_modules/appdmg/bin/appdmg.js
> macos-alias@0.2.11 install /Users/travis/.npm-global/lib/node_modules/appdmg/node_modules/macos-alias
> node-gyp rebuild
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/volume/src/volume.o
  SOLINK_MODULE(target) Release/volume.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
> fs-xattr@0.3.0 install /Users/travis/.npm-global/lib/node_modules/appdmg/node_modules/fs-xattr
> node-gyp rebuild
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CC(target) Release/obj.target/xattr/src/async.o
In file included from ../src/async.c:6:
../src/error.h:5:10: fatal error: 'node_api.h' file not found
#include <node_api.h>
         ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/xattr/src/async.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/travis/.nvm/versions/node/v6.11.5/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/travis/.nvm/versions/node/v6.11.5/bin/node" "/Users/travis/.nvm/versions/node/v6.11.5/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/travis/.npm-global/lib/node_modules/appdmg/node_modules/fs-xattr
gyp ERR! node -v v6.11.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
/Users/travis/.npm-global/lib
└── (empty)
npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/travis/.nvm/versions/node/v6.11.5/bin/node" "/Users/travis/.nvm/versions/node/v6.11.5/bin/npm" "install" "-g" "appdmg"
npm ERR! node v6.11.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! fs-xattr@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fs-xattr@0.3.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fs-xattr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fs-xattr
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fs-xattr
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/travis/build/Mudlet/Mudlet/build/npm-debug.log
npm ERR! code 1
```

Is this something known?

**Comment by vadi2** [comment]
Hm - `command "/Users/travis/.nvm/versions/node/v6.11.5/bin/node"` perhaps we install it, but we don't use it!

**Comment by vadi2** [comment]
For anyone else looking at this - `npm upgrade node` wasn't doing the job, somehow an older binary was in the path first. We fixed it with `PATH=/usr/local/bin:$PATH` before `npm install -g appdmg`

**Comment by kefir500** [comment]
You can also install the latest NodeJS version with `nvm install node` in your Travis script.
