### ISSUE TITLE
can not install on macOS Catalina

### ISSUE THREAD

**Issue by kapitainsky** [LinusU/node-appdmg#187]
works perfectly well with the same Node 12 on Mojave but on Catalina when trying to install it always fails:

```
$ npm install -g appdmg
/usr/local/bin/appdmg -> /usr/local/lib/node_modules/appdmg/bin/appdmg.js

> macos-alias@0.2.11 install /usr/local/lib/node_modules/appdmg/node_modules/macos-alias
> node-gyp rebuild

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/appdmg/node_modules/macos-alias
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! macos-alias@0.2.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the macos-alias@0.2.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by kapitainsky** [comment]
reinstalling Command Line Tools for Xcode 11 from apple dev website solved all issues
