### ISSUE TITLE
ReferenceError: os is not defined

### ISSUE THREAD

**Issue by stakira** [LinusU/node-appdmg#206]
/Users/appveyor/.nvm/versions/node/v12.22.10/lib/node_modules/create-dmg/node_modules/appdmg/lib/appdmg.js:402
    if (os.arch() !== 'arm64') {
    ^
ReferenceError: os is not defined
    at Object.fn (/Users/appveyor/.nvm/versions/node/v12.22.10/lib/node_modules/create-dmg/node_modules/appdmg/lib/appdmg.js:402:5)
    at Pipeline._runStep (/Users/appveyor/.nvm/versions/node/v12.22.10/lib/node_modules/create-dmg/node_modules/appdmg/lib/pipeline.js:46:10)
    at Pipeline._run (/Users/appveyor/.nvm/versions/node/v12.22.10/lib/node_modules/create-dmg/node_modules/appdmg/lib/pipeline.js:94:10)
    at next (/Users/appveyor/.nvm/versions/node/v12.22.10/lib/node_modules/create-dmg/node_modules/appdmg/lib/pipeline.js:35:25)
    at /Users/appveyor/.nvm/versions/node/v12.22.10/lib/node_modules/create-dmg/node_modules/appdmg/lib/appdmg.js:390:74
    at /Users/appveyor/.nvm/versions/node/v12.22.10/lib/node_modules/create-dmg/node_modules/ds-store/lib/ds-store.js:291:7
    at /Users/appveyor/.nvm/versions/node/v12.22.10/lib/node_modules/create-dmg/node_modules/graceful-fs/graceful-fs.js:61:14

**Comment by stakira** [comment]
@cybergrind

**Comment by LinusU** [comment]
Fixed in [🚢 0.6.4 / 2022-03-17](https://github.com/LinusU/node-appdmg/releases/tag/v0.6.4), sorry about the breakage!

**Comment by stakira** [comment]
Thanks!

**Comment by cybergrind** [comment]
sorry, it was working during my tests. probably different node version or smth
