### ISSUE TITLE
Module version mismatch. Expected 47, got 14.

### ISSUE THREAD

**Issue by eric-naguras** [LinusU/node-appdmg#75]
It used to work but I upgraded to node 5. Now I get this error. Is there a workaround?

$ appdmg test/appdmg.json ~/Desktop/test.dmg
module.js:450
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 47, got 14.
    at Error (native)
    at Object.Module._extensions..node (module.js:450:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/appdmg/node_modules/ds-store/node_modules/macos-alias/lib/create.js:7:13)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)

**Comment by LinusU** [comment]
When you upgrade node version you need to reinstall all of your packages. This is unfortunately nothing I can fix here...

```sh
npm rm -g appdmg
npm i -g appdmg
```
