### ISSUE TITLE
Error [object Object]

### ISSUE THREAD

**Issue by gsantome** [LinusU/node-appdmg#90]
Hello, I'm having some problems with the latest version of appdmg, It was working and for some reason now I'm getting an error but I can't see whats happened.

![appdmg-error](https://cloud.githubusercontent.com/assets/2914973/13732562/157cffa0-e95c-11e5-9c42-009755832e89.png)

When I'm trying --verbose I started to see this error

```
Error: Error running `hdiutil`! Exit code was 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/appdmg/lib/util.js:30:17)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

Thanks!

**Comment by gsantome** [comment]
I'm closing the issue because I found I need to have the folder first
